name: Build and Publish Containers

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
#          - name: backend
#            dockerfile: ./selfhosted/Dockerfile.backend
#          - name: backend-cpu
#            dockerfile: ./selfhosted/Dockerfile.backend.cpu
#          - name: frontend
#            dockerfile: ./selfhosted/Dockerfile.frontend
          - name: vast
            dockerfile: ./selfhosted/Dockerfile.vast

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./selfhosted
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.name }}:latest
            ghcr.io/${{ github.repository }}-${{ matrix.name }}:${{ github.sha }}
          secrets: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
